const { fakerEN_US: faker } = require("@faker-js/faker");
const { Product } = require("../models");

module.exports = async () => {
  const products = [];

  products.push(
    {
      name: "The Fall of Troy",
      tracklist: [
        "Rockstar Nailbomb!",
        "Spartacus",
        "The Circus That Has Brought Us Back To These Nights (Yo Chocola)",
        "Mouths Like Sidewinder Missiles",
        "The Last March Of The Ents",
        "F.C.P.S.I.T.S.G.E.P.G.E.P.G.E.P.",
        "Whacko Jacko Steals The Elephant Man's Bones",
        "Reassurance Rests In The Sea",
        "The Adventures Of Allan Gordon",
        "I Just Got This Symphony Goin'",
        "What Sound Does A Mastodon Make?",
      ],
      image: "the-fall-of-troy-1.webp",
      price: 25,
      stock: 10,
      featured: false,
      artistId: 1,
      categoryId: 2,
    },
    {
      name: "Doppelganger",
      tracklist: [
        "I Just Got This Symphony Goin'",
        "Act One, Scene One",
        "F.C.P.R.E.M.I.X.",
        "'You Got A Death Wish, Johnny Truant?'",
        "Mouths Like Sidewinder Missiles",
        "The Hol[ ]y Tape...",
        "Laces Out, Dan!",
        "We Better Learn To Hotwire A Uterus",
        "Whacko Jacko Steals The Elephant Man's Bones",
        "Tom Waits",
        "Macaulay McCulkin",
      ],
      image: "the-fall-of-troy-2.webp",
      price: 25,
      stock: 10,
      featured: false,
      artistId: 1,
      categoryId: 2,
    },
    {
      name: "Divine Inner Tension",
      tracklist: [
        "Tunnel Vision Alibi",
        "Mind Rider",
        "Chunker",
        "60-Minute Session Blocks",
        "Maladapted",
        "The Story Writes Itself",
        "(In My Dream)",
        "I Saw You Hanging",
        "Tithe",
        "Feeble Words",
        "Little Song",
        "Under the Floor",
      ],
      image: "hail-the-sun-1.webp",
      price: 25,
      stock: 10,
      featured: true,
      artistId: 2,
      categoryId: 2,
    },
    {
      name: "Mental Knife",
      tracklist: [
        "Gouge & Uproot",
        "Mental Knife",
        "Suffocating Syndrome",
        "Devotion Cuts",
        "The Stranger In Our Pictures",
        "A Lesson In Lust",
        "RIsk/Reward",
        "Feel It When Convenient",
        "Arcane Justice",
        "Half Empty",
        "On Existence",
      ],
      image: "hail-the-sun-2.webp",
      price: 25,
      stock: 10,
      featured: false,
      artistId: 2,
      categoryId: 2,
    },
    {
      name: "New Age Filth",
      tracklist: [
        "Domino",
        "Slander",
        "Solipsism",
        "Misfire",
        "Made Your Mark",
        "Slipped My Mind",
        "Parasitic Cleanse",
        "Hysteriantics",
        "Devaluation",
        "Punch Drunk",
      ],
      image: "hail-the-sun-3.webp",
      price: 25,
      stock: 10,
      featured: false,
      artistId: 2,
      categoryId: 2,
    },
    {
      name: "The Rain Museum",
      tracklist: [
        "The Rain Museum",
        "How Far Apart",
        "See You On The Other Side",
        "World Burn Down",
        "In This Nightmare Together",
        "New Rainbows",
        "I\u2019m Not Myself",
        "Whatever, Who Cares",
        "Rather Down",
        "A Teardrop (On The Surface Of The Sun)",
        "Tomorrow Faded Away",
        "Spinning Through Time",
      ],
      image: "armor-for-sleep-1.webp",
      price: 25,
      stock: 10,
      featured: true,
      artistId: 3,
      categoryId: 3,
    },
    {
      name: "Dream to Make Believe",
      tracklist: [
        "Armor for Sleep (instrumental)",
        "Dream to Make Believe",
        "All Warm",
        "Being Your Walls",
        "My Town",
        "The Wanderer's Guild",
        "Frost and Front Steps",
        "Phantoms Now",
        "Raindrops",
        "Kind of Perfect",
        "Slip Like Space",
      ],
      image: "armor-for-sleep-2.webp",
      price: 25,
      stock: 10,
      featured: false,
      artistId: 3,
      categoryId: 3,
    },
    {
      name: "Convinced",
      tracklist: ["Lacerate", "Decoder", "Banshee", "Animals", "Nothing More", "Etching"],
      image: "anberlin-1.webp",
      price: 25,
      stock: 10,
      featured: false,
      artistId: 4,
      categoryId: 3,
    },
    {
      name: "Silverline",
      tracklist: [
        "Two Graves",
        "Nothing Lost",
        "Body Language",
        "Asking Too Much",
        "Circles",
        "Etching",
      ],
      image: "anberlin-2.webp",
      price: 25,
      stock: 10,
      featured: false,
      artistId: 4,
      categoryId: 3,
    },
    {
      name: "Don't Wait Up",
      tracklist: [
        "Non-Negotiable",
        "All the Way Through",
        "Calling Hours",
        "Park St.",
        "What Awaits Us Now",
        "Hard to Find",
        "Lost at Sea",
        "Post Hoc",
        "Wrong Planet",
        "Final Backwards Glance",
      ],
      image: "bane-1.webp",
      price: 25,
      stock: 10,
      featured: true,
      artistId: 5,
      categoryId: 1,
    },
    {
      name: "Give Blood",
      tracklist: [
        "Speechless",
        "Some Came Running",
        "Snakes Among Us",
        "Release the Hounds",
        "What Holds Us Down",
        "Ante Up",
        "Bang the Drum Slowly",
        "Sunflowers and Sunsets",
        "The Big Gun Down",
        "Ali v. Frazier",
      ],
      image: "bane-2.webp",
      price: 25,
      stock: 10,
      featured: false,
      artistId: 5,
      categoryId: 1,
    },
    {
      name: "Cold",
      tracklist: [
        "Champions",
        "Cursed",
        "Machines",
        "Freedom",
        "The Game",
        "Cold",
        "Watch Me Sink",
        "Pulling Teeth",
        "Walk Alone",
        "Scapegoat",
        "Thick Or Thin",
      ],
      image: "gideon-1.webp",
      price: 25,
      stock: 10,
      featured: false,
      artistId: 6,
      categoryId: 1,
    },
    {
      name: "More Power. More Pain.",
      tracklist: [
        "Hell For A Man",
        "Locked Out Of Heaven",
        "Push It Back",
        "Too Much Is Never Enough",
        "MORE POWER. MORE PAIN.",
        "Take Off",
        "Damned If I Do (Damned If I Don't)",
        "If You Love Me, Let Me Go",
        "Off The Rails",
        "The Final Nail",
        "Midnight Blue",
        "I Will Carry You",
        "Back 2 Basics",
        "Let 'Er Fly",
      ],
      image: "gideon-2.webp",
      price: 25,
      stock: 10,
      featured: false,
      artistId: 6,
      categoryId: 1,
    },
    {
      name: "The Weight and the Cost",
      tracklist: [
        "Meaningless Measures",
        "Magic",
        "Strength For Breath",
        "Tiny Little Pieces",
        "Morning Light",
        "The Weight and the Cost",
        "Each Passing Day",
        "Frozen",
        "Aperture",
        "Longing",
        "Confessional",
      ],
      image: "be-well-1.webp",
      price: 25,
      stock: 10,
      featured: true,
      artistId: 7,
      categoryId: 1,
    },
    {
      name: "Deluge",
      tracklist: ["Untethered", "No Safe Corners", "Pass of Redress", "Control"],
      image: "fairweather-1.webp",
      price: 25,
      stock: 10,
      featured: false,
      artistId: 8,
      categoryId: 1,
    },
    {
      name: "Empty Black",
      tracklist: [
        "Sweet Machine",
        "Blemish",
        "Echo And Dust Pt. I",
        "Mortality Rate",
        "Ten Dogs \u2014 Red Heaven",
        "White Lighters",
        "Kappa (River Child)",
        "Day Is Gone",
        "Broadcast Network",
        "Echo And Dust Pt. II",
      ],
      image: "greyhaven-1.webp",
      price: 25,
      stock: 10,
      featured: true,
      artistId: 9,
      categoryId: 2,
    },
    {
      name: "Kodak",
      tracklist: [
        "Clinical Trials",
        "Feeling Well",
        "DFR",
        "State Of Abuses",
        "Soma",
        "Walk Me Through It",
        "AA Almanac",
        "Sumter",
        "Quitter Talk",
        "Know Your Tell",
      ],
      image: "all-get-out-1.webp",
      price: 25,
      stock: 10,
      featured: false,
      artistId: 10,
      categoryId: 3,
    },
    {
      name: "Dena Mora",
      tracklist: [
        "Youth, Too Late",
        "Floor Of Tradition",
        "El Shakes",
        "Whe We Leave",
        "Filthy Doves",
        "Krampus",
        "Mellow Christ",
        "Mid-Brain Reward System",
        "Dena Mora",
        "Nomad Motto",
        "Decathect",
      ],
      image: "idlehands-1.webp",
      price: 25,
      stock: 10,
      featured: false,
      artistId: 11,
      categoryId: 3,
    },
    {
      name: "Texas in July",
      tracklist: [
        "Initiate",
        "Cry Wolf",
        "Shallow Point",
        "Without A Head",
        "Bed Of Nails",
        "Repressed Memories",
        "C4",
        "Crux Lust",
        "Paranoia",
        "Black Magic",
        "Cloudy Minds",
      ],
      image: "texas-in-july-1.webp",
      price: 25,
      stock: 10,
      featured: false,
      artistId: 12,
      categoryId: 4,
    },
    {
      name: "Without Reason",
      tracklist: ["False Divinity", "Razors Edge", "Put to Death", "Digital Hellscape", "Goodbye"],
      image: "texas-in-july-2.webp",
      price: 25,
      stock: 10,
      featured: false,
      artistId: 12,
      categoryId: 4,
    },
    {
      name: "Bloodwork",
      tracklist: [
        "Broken Soul",
        "Sweetest Poison",
        "Pseudo Self",
        "Defenseless",
        "The Void",
        "Inner Demons",
        "Decamilli",
        "Nooses",
        "The Tightrope",
        "Illuminate",
        "Bloodwork",
      ],
      image: "texas-in-july-3.webp",
      price: 25,
      stock: 10,
      featured: false,
      artistId: 12,
      categoryId: 4,
    },
    {
      name: "To Plant a Seed",
      tracklist: [
        "To Plant A Seed ",
        "Broken Statues ",
        "Intentions ",
        "Roads That Don't End And Views That Never Cease ",
        "Dreams",
        "We Are The Reasons ",
        "Beliefs ",
        "I Will Not Reap Destruction ",
        "Searching, Seeking, Reaching, Always ",
        "An Ever-Growing Wonder",
      ],
      image: "we-came-as-romans-1.webp",
      price: 25,
      stock: 10,
      featured: false,
      artistId: 13,
      categoryId: 4,
    },
    {
      name: "A Flair for the Dramatic",
      tracklist: [
        "Chemical Kids and Mechanical Brides",
        "Currents Convulsive",
        "Yeah Boy and Doll Face",
        "I'd Rather Die Than Be Famous",
        "The Cheap Bouquet",
        "Falling Asleep on a Stranger",
        "She Sings in the Morning",
        "The Balcony Scene",
        "Drella",
        "Diamonds and Why Men Buy Them",
        "Wonderless",
      ],
      image: "pierce-the-veil-1.webp",
      price: 25,
      stock: 10,
      featured: false,
      artistId: 14,
      categoryId: 5,
    },
    {
      name: "Entertainment",
      tracklist: [
        "11:11 ",
        "Blonde ",
        "Peach (Lobotomy) ",
        "We Need To Talk ",
        "Not Warriors ",
        "Lucky People ",
        "Rare",
        "TANTRUM ",
        "Crybaby ",
        "Sleep Alone",
      ],
      image: "waterparks-1.webp",
      price: 25,
      stock: 10,
      featured: false,
      artistId: 15,
      categoryId: 5,
    },
    {
      name: "Double Dare",
      tracklist: [
        "Hawaii (Stay Awake) ",
        "Gloom Boys ",
        "Stupid For You ",
        "Royal ",
        "Take Her to the Moon ",
        "Made In America ",
        "Dizzy ",
        "Powerless ",
        "Little Violence ",
        "21 Questions ",
        "It Follows ",
        "Plum Island ",
        "I'll Always Be Around",
      ],
      image: "waterparks-2.webp",
      price: 25,
      stock: 10,
      featured: false,
      artistId: 15,
      categoryId: 5,
    },
  );

  await Product.bulkCreate(products);
  console.log("[Database] Product seeder executed successfully.");
};
